package com.javarush.task.task07.task0724;                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
/*                                                                                                                                                                                                                                                                                                             
Семейная перепись                                                                                                                                                                                                                                                                                                            
*/                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
public class Solution {                                                                                                                                                                                                                                                                                                            
    public static void main(String[] args) {                                                                                                                                                                                                                                                                                                            
        Human human = new Human("Наташа", false, 34);                                                                                                                                                                                                        
        Human human1 = new Human("Сергей", true, 37);                                                                                                                                                                                                        
        Human human2 = new Human("Майя", false, 3);                                                                                                                                                                                                        
        Human human3 = new Human("Саня", true, 37);                                                                                                                                                                                                        
        Human human4 = new Human("Моня", true, 30, human, human1);                                                                                                                                                                                                        
        Human human5 = new Human("Маня", false, 20, human1, human);                                                                                                                                                                                                        
        Human human6 = new Human("Никита", true, 37, human3, human2);                                                                                                                                                                                                        
        Human human7 = new Human("Димон", true, 36, human4, human5);                                                                                                                                                                                                        
        Human human8 = new Human("Толян", true, 35, human7, human);                                                                                                                                                                                                        
                                                                                                                                                                                                                
        System.out.println(human);                                                                                                                                                                                                        
        System.out.println(human1);                                                                                                                                                                                                        
        System.out.println(human2);                                                                                                                                                                                                        
        System.out.println(human3);                                                                                                                                                                                                        
        System.out.println(human4);                                                                                                                                                                                                        
        System.out.println(human5);                                                                                                                                                                                                        
        System.out.println(human6);                                                                                                                                                                                                        
        System.out.println(human7);                                                                                                                                                                                                        
        System.out.println(human8);                                                                                                                                                                                                        
        // напишите тут ваш код                                                                                                                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
    public static class Human {                                                                                                                                                                                                                                                                                                            
        String name;                                                                                                                                                                                                        
        boolean sex;                                                                                                                                                                                                        
        int age;                                                                                                                                                                                                        
        Human father;                                                                                                                                                                                                        
        Human mother;                                                                                                                                                                                                        
                                                                                                                                                                                                        
        public Human(String name, boolean sex, int age) {                                                                                                                                                                                                        
            this.name = name;                                                                                                                                                                                                        
            this.sex = sex;                                                                                                                                                                                                        
            this.age = age;                                                                                                                                                                                                        
        }                                                                                                                                                                                                        
                                                                                                                                                                                                        
        public Human(String name, boolean sex, int age, Human father, Human mother) {                                                                                                                                                                                                        
            this.name = name;                                                                                                                                                                                                        
            this.sex = sex;                                                                                                                                                                                                        
            this.age = age;                                                                                                                                                                                                        
            this.father = father;                                                                                                                                                                                                        
            this.mother = mother;                                                                                                                                                                                                        
        }                                                                                                                                                                                                        
                                                                                                                                                                                                        
// напишите тут ваш код                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
        public String toString() {                                                                                                                                                                                                                                                                                                            
            String text = "";                                                                                                                                                                                                                                                                                                            
            text += "Имя: " + this.name;                                                                                                                                                                                                                                                                                                            
            text += ", пол: " + (this.sex ? "мужской" : "женский");                                                                                                                                                                                                                                                                                                            
            text += ", возраст: " + this.age;                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
            if (this.father != null) {                                                                                                                                                                                                                                                                                                            
                text += ", отец: " + this.father.name;                                                                                                                                                                                                                                                                                                            
            }                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
            if (this.mother != null) {                                                                                                                                                                                                                                                                                                            
                text += ", мать: " + this.mother.name;                                                                                                                                                                                                                                                                                                            
            }                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
            return text;                                                                                                                                                                                                                                                                                                            
        }                                                                                                                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                                                                                            
}                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
