package com.javarush.task.task08.task0813;                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                              
import java.util.Set;                                                                                                                                                                                                                                                          
import java.util.HashSet;                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                              
/*                                                                                                                                                                                                                                                                                                                                                               
20 слов на букву «Л»                                                                                                                                                                                                                                                                                                                                                              
*/                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                              
public class Solution {                                                                                                                                                                                                                                                                                                                                                              
    public static Set<String> createSet() {                                                                                                                                                                                                                                                                                                                                                              
        Set<String> set = new HashSet<>();                                                                                                                                                                                                                                                                                                            
        set.add("Любовь");                                                                                                                                                                                                                                                                                                            
        set.add("Лоск");                                                                                                                                                                                                                                                                                                            
        set.add("Лера");                                                                                                                                                                                                                                                                                                            
        set.add("Лампа");                                                                                                                                                                                                                                                                                                            
        set.add("Ломтик");                                                                                                                                                                                                                                                                                                            
        set.add("Лось");                                                                                                                                                                                                                                                                                                            
        set.add("Ларек");                                                                                                                                                                                                                                                                                                            
        set.add("Лещ");                                                                                                                                                                                                                                                                                                            
        set.add("Лосось");                                                                                                                                                                                                                                                                                                            
        set.add("Лиман");                                                                                                                                                                                                                                                                                                            
        set.add("Лавр");                                                                                                                                                                                                                                                                                                            
        set.add("Лето");                                                                                                                                                                                                                                                                                                            
        set.add("Ласка");                                                                                                                                                                                                                                                                                                            
        set.add("Лор");                                                                                                                                                                                                                                                                                                            
        set.add("Лужа");                                                                                                                                                                                                                                                                                                            
        set.add("Лук");                                                                                                                                                                                                                                                                                                            
        set.add("Леска");                                                                                                                                                                                                                                                                                                            
        set.add("Ловля");                                                                                                                                                                                                                                                                                                            
        set.add("Лена");                                                                                                                                                                                                                                                                                                            
        set.add("Липа");                                                                                                                                                                                                                                                                                                            
        return set;                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                    
        //напишите тут ваш код                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                              
    }                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                              
    public static void main(String[] args) {                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                              
    }                                                                                                                                                                                                                                                                                                                                                              
}                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
