package com.javarush.task.task08.task0812;                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                              
import java.io.IOException;                                                                                                                                                                                                                                                            
import java.io.BufferedReader;                                                                                                                                                                                                                                                          
import java.io.InputStreamReader;                                                                                                                                                                                                          
import java.util.List;                                                                                                     
import java.util.ArrayList;                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                              
/*                                                                                                                                                                                                                                                                                                                                                               
Cамая длинная последовательность                                                                                                                                                                                                                                                                                                                                                              
*/                                                                                                                                                                                                                                                                                                                                                              
public class Solution {                                                                                                                                                                                                                                                                                                                                                              
    public static void main(String[] args) throws IOException {                                                                                                                                                                                                                                                             
        BufferedReader buff = new BufferedReader(new InputStreamReader(System.in));                                                                                                                                                                                                                                                                                                                                                           
        List<Integer> list = new ArrayList<>();                                                                                                                                                                                                                                                          
        for (int i = 0; i < 10; i++)                                                                                                                                                                                                                                                           
            list.add(Integer.parseInt(buff.readLine()));                                                                                                                                                                                                        
        int cont = 1;                                                                                                                                                      
        int max = 1;                                                                                                                                                                                                        
        for (int i = 0; i < list.size() - 1; i++) {                                                                                                                                                                                                        
        if (list.get(i).equals(list.get(i + 1)))                                                                                                                                                      
        {                                                                                                                                                                                                        
        cont++;                                                                                                                                                        
        if (cont > max)                                                                                                                                                      
        max = cont;                                                                                                                                                      
        }                                                                                                                                                      
        else                                                                                                                                                      
        cont = 1;                                                                                                                                                      
                                                                                                                                                                                                              
        }                                                                                                                                                                                                        
        System.out.println(max);                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                            
        //напишите тут ваш код                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                              
    }                                                                                                                                                                                                                                                                                                                                                              
}                                                  
                                            
