package com.javarush.task.task07.task0709;                                                                                                                                                                                                                                                          
import java.util.ArrayList;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
import java.io.BufferedReader;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
import java.io.InputStreamReader;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                            
/*                                                                                                                                                                                                                                                           
Выражаемся покороче                                                                                                                                                                                                                                                          
*/                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                          
public class Solution {                                                                                                                                                                                                                                                          
    public static void main(String[] args) throws Exception {                                                                                                                                                                                                                                                          
        BufferedReader buff = new BufferedReader(new InputStreamReader(System.in));                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        ArrayList<String> strings = new ArrayList<String>();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
            for (int i = 0; i < 5; i++){                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                strings.add(buff.readLine());                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
            }                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
        int min = strings.get(0).length();                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                      
            for (int i = 1; i < strings.size(); i++) {                                                                                                                                                                                                                                                                                                                                                              
                if(strings.get(i).length() <= min)                                                                                                                                                                                                                                                                                                                                                              
                    min = strings.get(i).length();                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                          
            }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
            for (int i = 0; i < strings.size(); i++) {                                                                                                                                                                                                                                                                                                                                                              
                if(strings.get(i).length() == min)                                                                                                                                                                                                                                                                                                                                                              
                    System.out.println(strings.get(i));                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                          
            }                                           //напишите тут ваш код                                                                                                                                                                                                                                                          
    }                                                                                                                                                                                                                                                          
}                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  
